export type {
  PropostaStatus,
  EscritorioPerfil,
  MaturidadeProcessos,
  MaturidadeIA,
  AreaAtuacao,
  PrecoFaixa,
  DorId,
  Profile,
  Proposta,
  PropostaView,
  PropostaActivity,
  PropostaFormData,
  ROICalculation,
} from './database';
